/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.astralsmp;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        AstralThread classUnderTest = new AstralThread();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
